2025-09-12 15:40:38,653 INFO    MainThread:3839170 [wandb_setup.py:_flush():80] Current SDK version is 0.21.1
2025-09-12 15:40:38,653 INFO    MainThread:3839170 [wandb_setup.py:_flush():80] Configure stats pid to 3839170
2025-09-12 15:40:38,653 INFO    MainThread:3839170 [wandb_setup.py:_flush():80] Loading settings from /home/ktshim/.config/wandb/settings
2025-09-12 15:40:38,653 INFO    MainThread:3839170 [wandb_setup.py:_flush():80] Loading settings from /nas/home/ktshim/tool/pool/graphtoken/wandb/settings
2025-09-12 15:40:38,653 INFO    MainThread:3839170 [wandb_setup.py:_flush():80] Loading settings from environment variables
2025-09-12 15:40:38,653 INFO    MainThread:3839170 [wandb_init.py:setup_run_log_directory():703] Logging user logs to /nas/home/ktshim/tool/pool/graphtoken/wandb/run-20250912_154038-y6pxujdk/logs/debug.log
2025-09-12 15:40:38,654 INFO    MainThread:3839170 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to /nas/home/ktshim/tool/pool/graphtoken/wandb/run-20250912_154038-y6pxujdk/logs/debug-internal.log
2025-09-12 15:40:38,654 INFO    MainThread:3839170 [wandb_init.py:init():830] calling init triggers
2025-09-12 15:40:38,654 INFO    MainThread:3839170 [wandb_init.py:init():835] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-09-12 15:40:38,654 INFO    MainThread:3839170 [wandb_init.py:init():871] starting backend
2025-09-12 15:40:38,861 INFO    MainThread:3839170 [wandb_init.py:init():874] sending inform_init request
2025-09-12 15:40:38,866 INFO    MainThread:3839170 [wandb_init.py:init():882] backend started and connected
2025-09-12 15:40:38,868 INFO    MainThread:3839170 [wandb_init.py:init():953] updated telemetry
2025-09-12 15:40:38,880 INFO    MainThread:3839170 [wandb_init.py:init():977] communicating run to backend with 90.0 second timeout
2025-09-12 15:40:39,596 INFO    MainThread:3839170 [wandb_init.py:init():1029] starting run threads in backend
2025-09-12 15:40:39,646 INFO    MainThread:3839170 [wandb_run.py:_console_start():2494] atexit reg
2025-09-12 15:40:39,646 INFO    MainThread:3839170 [wandb_run.py:_redirect():2342] redirect: wrap_raw
2025-09-12 15:40:39,646 INFO    MainThread:3839170 [wandb_run.py:_redirect():2411] Wrapping output streams.
2025-09-12 15:40:39,646 INFO    MainThread:3839170 [wandb_run.py:_redirect():2434] Redirects installed.
2025-09-12 15:40:39,647 INFO    MainThread:3839170 [wandb_init.py:init():1075] run started, returning control to user process
2025-09-12 16:06:36,432 INFO    MsgRouterThr:3839170 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-09-12 16:06:38,524 ERROR   MainThread:3839170 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/ktshim/.local/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/ktshim/.local/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ktshim/.local/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ktshim/.local/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ktshim/.local/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/ktshim/.local/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 770, in publish_output_raw
    o.timestamp.GetCurrentTime()
  File "/home/ktshim/.local/lib/python3.12/site-packages/google/protobuf/internal/well_known_types.py", line 184, in GetCurrentTime
    self.FromDatetime(datetime.datetime.now(tz=datetime.timezone.utc))
  File "/home/ktshim/.local/lib/python3.12/site-packages/google/protobuf/internal/well_known_types.py", line 283, in FromDatetime
    seconds = calendar.timegm(dt.utctimetuple())
                              ^^^^^^^^^^^^^^^^^
ModuleNotFoundError: import of time halted; None in sys.modules
2025-09-12 16:06:38,528 ERROR   MainThread:3839170 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/ktshim/.local/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/ktshim/.local/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ktshim/.local/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ktshim/.local/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ktshim/.local/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/ktshim/.local/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 770, in publish_output_raw
    o.timestamp.GetCurrentTime()
  File "/home/ktshim/.local/lib/python3.12/site-packages/google/protobuf/internal/well_known_types.py", line 184, in GetCurrentTime
    self.FromDatetime(datetime.datetime.now(tz=datetime.timezone.utc))
  File "/home/ktshim/.local/lib/python3.12/site-packages/google/protobuf/internal/well_known_types.py", line 283, in FromDatetime
    seconds = calendar.timegm(dt.utctimetuple())
                              ^^^^^^^^^^^^^^^^^
ModuleNotFoundError: import of time halted; None in sys.modules
2025-09-12 16:06:38,529 ERROR   MainThread:3839170 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/ktshim/.local/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/ktshim/.local/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ktshim/.local/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ktshim/.local/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ktshim/.local/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/ktshim/.local/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 770, in publish_output_raw
    o.timestamp.GetCurrentTime()
  File "/home/ktshim/.local/lib/python3.12/site-packages/google/protobuf/internal/well_known_types.py", line 184, in GetCurrentTime
    self.FromDatetime(datetime.datetime.now(tz=datetime.timezone.utc))
  File "/home/ktshim/.local/lib/python3.12/site-packages/google/protobuf/internal/well_known_types.py", line 283, in FromDatetime
    seconds = calendar.timegm(dt.utctimetuple())
                              ^^^^^^^^^^^^^^^^^
ModuleNotFoundError: import of time halted; None in sys.modules
2025-09-12 16:06:38,529 ERROR   MainThread:3839170 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/ktshim/.local/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/ktshim/.local/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ktshim/.local/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ktshim/.local/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ktshim/.local/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/ktshim/.local/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 770, in publish_output_raw
    o.timestamp.GetCurrentTime()
  File "/home/ktshim/.local/lib/python3.12/site-packages/google/protobuf/internal/well_known_types.py", line 184, in GetCurrentTime
    self.FromDatetime(datetime.datetime.now(tz=datetime.timezone.utc))
  File "/home/ktshim/.local/lib/python3.12/site-packages/google/protobuf/internal/well_known_types.py", line 283, in FromDatetime
    seconds = calendar.timegm(dt.utctimetuple())
                              ^^^^^^^^^^^^^^^^^
ModuleNotFoundError: import of time halted; None in sys.modules
2025-09-12 16:06:38,530 ERROR   MainThread:3839170 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/ktshim/.local/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/ktshim/.local/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ktshim/.local/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ktshim/.local/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ktshim/.local/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/ktshim/.local/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 770, in publish_output_raw
    o.timestamp.GetCurrentTime()
  File "/home/ktshim/.local/lib/python3.12/site-packages/google/protobuf/internal/well_known_types.py", line 184, in GetCurrentTime
    self.FromDatetime(datetime.datetime.now(tz=datetime.timezone.utc))
  File "/home/ktshim/.local/lib/python3.12/site-packages/google/protobuf/internal/well_known_types.py", line 283, in FromDatetime
    seconds = calendar.timegm(dt.utctimetuple())
                              ^^^^^^^^^^^^^^^^^
ModuleNotFoundError: import of time halted; None in sys.modules
2025-09-12 16:06:38,530 ERROR   MainThread:3839170 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/ktshim/.local/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/ktshim/.local/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ktshim/.local/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ktshim/.local/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ktshim/.local/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/ktshim/.local/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 770, in publish_output_raw
    o.timestamp.GetCurrentTime()
  File "/home/ktshim/.local/lib/python3.12/site-packages/google/protobuf/internal/well_known_types.py", line 184, in GetCurrentTime
    self.FromDatetime(datetime.datetime.now(tz=datetime.timezone.utc))
  File "/home/ktshim/.local/lib/python3.12/site-packages/google/protobuf/internal/well_known_types.py", line 283, in FromDatetime
    seconds = calendar.timegm(dt.utctimetuple())
                              ^^^^^^^^^^^^^^^^^
ModuleNotFoundError: import of time halted; None in sys.modules
